/*
 * @Author: Zhouyang Meng
 * @Date: 2024-05-13 10:17:37
 * @LastEditTime: 2024-05-15 17:27:25
 * @Description:
 *
 * Copyright (c) 2024 by YuyakeSys, All Rights Reserved.
 */
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./admin/authContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>{children}</body>
      </AuthProvider>
    </html>
  );
}
