name: CI/CD Pipeline

on:
  push:
    branches:
      - AWS
  pull_request:
    branches:
      - AWS

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t chestermeng/client ./client
          docker build -t chestermeng/api ./backend
          docker build -t chestermeng/admin ./admin
          docker push chestermeng/client
          docker push chestermeng/api
          docker push chestermeng/admin

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull your-dockerhub-username/client
            docker pull your-dockerhub-username/api
            docker pull your-dockerhub-username/admin
            cd /path/to/your/docker-compose-directory
            docker-compose down
            docker-compose up -d
