name: CI/CD Pipeline

on:
  push:
    branches:
      - AWS
  pull_request:
    branches:
      - AWS

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Clean up unused Docker resources
            docker system prune -af --volumes

            # Remove unused images
            docker image prune -af

            # Remove unused volumes
            docker volume prune -f

            # Remove unused networks
            docker network prune -f

            # Display disk usage information
            df -h
            cd ConexusDocker
            git pull
            docker-compose down
            docker-compose pull
            docker-compose up --build -d

            docker-compose logs

# test
# docker pull chestermeng/client
# docker pull chestermeng/api
# docker pull chestermeng/admin
